[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe", "@supabase/supabase-js"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
